Samples/CSharp/C# Hive Samples/MVC/web/Controllers/Iteration/IterationController.cs
#region Copyright Syncfusion Inc. 2001 - 2016
// Copyright Syncfusion Inc. 2001 - 2016. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCSampleBrowser.Models;
using Syncfusion.ThriftHive.Base;
namespace MVCSampleBrowser.Controllers
{
    public class IterationController : Controller
    {
        public static string ErrorMessage
        { get; set; }
        public ActionResult IterationDefault()
        {
            ErrorMessage = "";
            return View();
         }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult IterationDefault(string dumpbutton)
        {
            ErrorMessage="";
            string path = new System.IO.DirectoryInfo(Request.PhysicalPath + "..\\..\\..\\..\\..\\..\\..\\Data\\AdventureWorks\\AdventureWorks_Person_Contact.csv").FullName;
             CheckFileStatus CheckFile = new CheckFileStatus();
            ErrorMessage = CheckFile.CheckFile(path);
            if (ErrorMessage == "")
            {
                try
                {
                    //Binding the result to the rich text editor
                    var DataSource = CustomersData.list();
                    ViewBag.datasource = DataSource;
                    ErrorMessage = "";
                }
                catch (HqlConnectionException)
                {
                    ErrorMessage = "Could not establish a connection to the HiveServer. Please run HiveServer2 from the Syncfusion service manager dashboard.";

                }
            }
            return View();
        }
    }
}

Samples/CSharp/C# Hive Samples/MVC/web/Views/Iteration/IterationDefault.cshtml
@section SampleHeading
{
   
}
<script></script>
</script>
@section ControlsSection{
   @{Html.BeginForm("IterationDefault", "Iteration", FormMethod.Post);
{
        <p>
            <strong>This sample demonstrates, how to fetch the records from the Hive table and iterate each tuple from the result and display the records</strong> <br />&nbsp;
            <input class="dumpButton" id="dumpButton" type="submit" value="Fetch" style="width: 120px;float:right"  />
        </p>
       <div style="color:red;padding-top:3px;padding-bottom:10px">@MVCSampleBrowser.Controllers.IterationController.ErrorMessage</div>
     
    Html.EndForm();
  }}
<body>
    <div id="showtable">
        @{Html.EJ().RTE("rteSample").Width("100%").Height("500%").AllowEditing(false).Locale("en-US").ShowToolbar(false).ContentTemplate(@<p>
        @if(ViewBag.DataSource!=null)   {
         <table border="1">
                <tr>
                    <th>ContactId</th>
                    <th>FullName</th>
                    <th>Age</th>
                    <th>Email Id</th>
                    <th>Phone Number</th>
                    <th>Last Modified Date</th>
                </tr>
                @foreach (PersonDetail Model in ViewBag.DataSource)
                {
                    <tr>
                        <td> @Model.ContactId</td>
                        <td> @Model.FullName</td>
                        <td> @Model.Age</td>
                        <td> @Model.EmailId</td>
                        <td> @Model.PhoneNumber</td>
                        <td> @Model.ModifiedDate</td>
                    </tr>
                }
            </table>}
        </p>).ShowFooter(false).Render();
            }
    </div>
</body>
}