Samples/CSharp/C# Hive Samples/MVC/web/Controllers/Export/ExportController.cs
#region Copyright Syncfusion Inc. 2001 - 2016
// Copyright Syncfusion Inc. 2001 - 2016. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Syncfusion.XlsIO;
using System.Drawing;
using System.Data;
using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;
using MVCSampleBrowser.Models;
using Syncfusion.ThriftHive.Base;
namespace MVCSampleBrowser.Controllers
{
    public class ExportController : Controller
    {
        public static string ErrorMessage
        { get; set; }
        #region Getting Started
        public ActionResult ExportDefault(string SaveOption)
        {
            if (SaveOption == null)
            {
                ErrorMessage = "";
                return View();
            }
            else if (SaveOption == "Excel 2013" || SaveOption == "Excel 2010" || SaveOption == "Excel 2007" || SaveOption == "Excel 2003" || SaveOption == "CSV")
            {
                ErrorMessage = "";
                string path = new System.IO.DirectoryInfo(Request.PhysicalPath + "..\\..\\..\\..\\..\\..\\..\\Data\\AdventureWorks\\AdventureWorks_Person_Contact.csv").FullName;
                CheckFileStatus CheckFile = new CheckFileStatus();
                ErrorMessage = CheckFile.CheckFile(path);
                if (ErrorMessage == "")
                {
                    try
                    {
                        //Instantiate the spreadsheet creation engine.
                        ExcelEngine excelEngine = new ExcelEngine();

                        //Instantiate the excel application object.
                        IApplication application = excelEngine.Excel;

                        //A new workbook is created.[Equivalent to creating a new workbook in MS Excel]
                        //The new workbook will have 1 worksheets
                        IWorkbook workbook = application.Workbooks.Create(1);

                        //The first worksheet object in the worksheets collection is accessed.
                        IWorksheet worksheet = workbook.Worksheets[0];
                        var result = CustomersData.list();
                        ErrorMessage = null;

                        //Adding header text for worksheet
                        worksheet[1, 1].Text = "Contact Id";
                        worksheet[1, 2].Text = "Full Name";
                        worksheet[1, 3].Text = "Age";
                        worksheet[1, 4].Text = "Phone Number";
                        worksheet[1, 5].Text = "Email Id";
                        worksheet[1, 6].Text = "Modified Date";

                        int i = 1;
                        //Reading each row from the fetched result
                        foreach (PersonDetail records in result)
                        {
                            //Reading each data from the row
                            //Assigning each data to the worksheet based on index
                            worksheet[i + 1, 1].Text = records.ContactId;
                            worksheet[i + 1, 2].Text = records.FullName;
                            worksheet[i + 1, 3].Text = records.Age;
                            worksheet[i + 1, 4].Text = records.PhoneNumber;
                            worksheet[i + 1, 5].Text = records.EmailId;
                            worksheet[i + 1, 6].Text = records.ModifiedDate;
                            i++;
                        }
                        //Assigning Header text with cell color
                        worksheet.Range["A1:F1"].CellStyle.Color = System.Drawing.Color.FromArgb(51, 153, 51);
                        worksheet.Range["A1:F1"].CellStyle.Font.Color = Syncfusion.XlsIO.ExcelKnownColors.White;
                        worksheet.Range["A1:F1"].CellStyle.Font.Bold = true;
                        worksheet.UsedRange.AutofitColumns();
        #endregion

                        //Save as .xls format
                        if (SaveOption == "Excel 2003")
                        {
                            return excelEngine.SaveAsActionResult(workbook, "Sample.xls", HttpContext.ApplicationInstance.Response, ExcelDownloadType.PromptDialog, ExcelHttpContentType.Excel97);
                        }
                        //Save as .xlsx format
                        else if (SaveOption == "Excel 2007")
                        {
                            workbook.Version = ExcelVersion.Excel2007;
                            return excelEngine.SaveAsActionResult(workbook, "Sample.xlsx", HttpContext.ApplicationInstance.Response, ExcelDownloadType.PromptDialog, ExcelHttpContentType.Excel2007);
                        }
                        //Save as .xlsx format
                        else if (SaveOption == "Excel 2010")
                        {
                            workbook.Version = ExcelVersion.Excel2010;
                            return excelEngine.SaveAsActionResult(workbook, "Sample.xlsx", HttpContext.ApplicationInstance.Response, ExcelDownloadType.PromptDialog, ExcelHttpContentType.Excel2010);
                        }
                        //Save as .xlsx format
                        else if (SaveOption == "Excel 2013")
                        {
                            workbook.Version = ExcelVersion.Excel2013;
                            return excelEngine.SaveAsActionResult(workbook, "Sample.xlsx", HttpContext.ApplicationInstance.Response, ExcelDownloadType.PromptDialog, ExcelHttpContentType.Excel2013);
                        }
                        //Save as .csv format
                        else if (SaveOption == "CSV")
                        {

                            return excelEngine.SaveAsActionResult(workbook, "Sample.csv", ",", HttpContext.ApplicationInstance.Response, ExcelDownloadType.PromptDialog, ExcelHttpContentType.CSV);
                        }
                        //Close the workbook
                        workbook.Close();

                        //Close the excelengine
                        excelEngine.Dispose();
                    }
                    catch (HqlConnectionException)
                    {
                        ErrorMessage = "Could not establish a connection to the HiveServer. Please run HiveServer2 from the Syncfusion service manager dashboard.";

                    }
                }

                return View();
            }
            else
            {
                ErrorMessage = "";
                string path = new System.IO.DirectoryInfo(Request.PhysicalPath + "..\\..\\..\\..\\..\\..\\..\\Data\\AdventureWorks\\AdventureWorks_Person_Contact.csv").FullName;
                CheckFileStatus CheckFile = new CheckFileStatus();
                ErrorMessage = CheckFile.CheckFile(path);
                //A new document is created.
                if (ErrorMessage == "")
                {
                    try
                    {
                        WordDocument document = new WordDocument();

                        //Adding new table to the document
                        WTable doctable = new WTable(document);

                        //Adding a new section to the document.
                        WSection section = document.AddSection() as WSection;

                        //Set Margin of the section
                        section.PageSetup.Margins.All = 72;

                        //Set page size of the section
                        section.PageSetup.PageSize = new SizeF(800, 792);

                        //Create Paragraph styles
                        WParagraphStyle style = document.AddParagraphStyle("Normal") as WParagraphStyle;
                        style.CharacterFormat.FontName = "Calibri";
                        style.CharacterFormat.FontSize = 11f;

                        //Reading the data from the table
                        var result = CustomersData.list();
                        doctable.AddRow(true, false);

                        //creating new cell
                        WTableCell cell = new WTableCell(document);

                        //Create a character format for declaring font color and style for the text inside the cell
                        WCharacterFormat charFormat = new WCharacterFormat(document);
                        charFormat.TextColor = System.Drawing.Color.White;
                        charFormat.Bold = true;

                        //Adding header text for the table
                        cell.AddParagraph().AppendText("Customer Id").ApplyCharacterFormat(charFormat);
                        cell.Width = 75;
                        cell.CellFormat.BackColor = System.Drawing.Color.FromArgb(51, 153, 51);
                        //Adding cell to rows
                        doctable.Rows[0].Cells.Add(cell);
                        cell = new WTableCell(document);
                        cell.AddParagraph().AppendText("Full Name").ApplyCharacterFormat(charFormat);
                        cell.Width = 90;
                        cell.CellFormat.BackColor = System.Drawing.Color.FromArgb(51, 153, 51);
                        doctable.Rows[0].Cells.Add(cell);
                        cell = new WTableCell(document);
                        cell.AddParagraph().AppendText("Age").ApplyCharacterFormat(charFormat);
                        cell.Width = 75;
                        cell.CellFormat.BackColor = System.Drawing.Color.FromArgb(51, 153, 51);
                        doctable.Rows[0].Cells.Add(cell);
                        cell = new WTableCell(document);
                        cell.AddParagraph().AppendText("Phone Number").ApplyCharacterFormat(charFormat);
                        cell.Width = 90;

Samples/CSharp/C# Hive Samples/MVC/web/Views/Export/ExportDefault.cshtml
@*@using Syncfusion.JavaScript.DataVisualization
@{
    ViewBag.Title = "Default";
    Layout = "~/Views/Shared/_Layout.cshtml";
}*@
@*<h2>Thrift Hive Sample</h2><br />*@
<div class="sampleheadingtext">
    <span class="sampletitle">Export as Excel/Word</span>
</div>
@section ControlsSection{

<script>
    $(document).ready(function () {
        $(".Word").hide();
        $("#Excel").click(function () {
            $(".Word").hide();
            $(".Excel").show();                    
        });
        $("#Word").click(function () {
            $(".Word").show();
            $(".Excel").hide();           
        });
    });
</script>
<div class="rowdiv">
    <label>
        This sample demonstrates the export of Hive table as Excel and Word documents
    </label>
    <div style="color:red;padding-top:3px;padding-bottom:10px">@MVCSampleBrowser.Controllers.ExportController.ErrorMessage</div>
</div><br />
<input type="radio" id="Excel" name="Group1" value="Excel" checked="checked" /><b>Excel</b>&nbsp; &nbsp; 
<input type="radio" id="Word" name="Group1" value="Word" /><b>Word</b>
<div class="Excel">
   
    @{Html.BeginForm("ExportDefault", "Export", FormMethod.Post);
    {
        <div class="Common">
            <div class="tablediv">                
                <br />
                <div class="rowdiv">
                    <div class="celldiv">
                        <label>
                            <strong> Save As:</strong>
                        </label><br />
                        <p>
                            <input id="rbtnCSV" type="radio" name="SaveOption" value="CSV" />  <b>CSV</b>&nbsp; &nbsp;
                            <input id="rbtn2003" type="radio" name="SaveOption" value="Excel 2003" />  <b>Excel 2003</b>&nbsp; &nbsp;
                            <input id="rbtn2007" type="radio" name="SaveOption" value="Excel 2007" />  <b>Excel 2007</b>&nbsp; &nbsp;
                            <input id="rbtn2010" type="radio" name="SaveOption" value="Excel 2010" />  <b>Excel 2010</b>&nbsp; &nbsp;
                            <input id="rbtn2013" type="radio" name="SaveOption" value="Excel 2013" checked="checked" />  <b>Excel 2013</b><br />
                        </p>
                    </div>
                    <br />
                    <div class="celldiv">
                        <input class="buttonStyle" type="submit" value="Export" style=" width:200px;" />
                    </div>
                    
                </div>
                <br />
            </div>
        </div>
        Html.EndForm();

    }
    
}
</div>
   

<div class="Word">
  
    @{Html.BeginForm("ExportDefault", "Export", FormMethod.Post);
{
    <div class="Common">
        <div class="tablediv">           
            <br />
            <div class="rowdiv">
                <div class="celldiv">
                    <label>
                        <strong>Save As </strong>
                    </label><br />
                    <p>
                        <input type="radio" id="rdButtonWord97To2003" name="SaveOption" value="Word 97-2003" />  <b>Word 97-2003</b>&nbsp; &nbsp;
                        <input type="radio" id="rdButtonWord2007" name="SaveOption" value="Word 2007" /> <b>Word 2007</b>&nbsp; &nbsp;
                        <input type="radio" id="rdButtonWord2010" name="SaveOption" value="Word 2010" /> <b>Word 2010</b>&nbsp; &nbsp;
                        <input type="radio" id="rdButtonWord2013" name="SaveOption" value="Word 2013" checked="checked" />   <b>Word 2013</b><br />
                    </p>

                </div>
                <br />
                <div class="celldiv">
                    <input class="buttonStyle" type="submit" value="Export" style="width: 200px;" />
                </div>
            </div>
            <br />
        </div>
    </div>
    Html.EndForm();
}}</div>}